### ISSUE TITLE
Synthetic CUBE test

### ISSUE THREAD

**Issue by ahmed-akader** [Algomorph/NeuralTracking#11]
- [x] make script that renders "twisted cube" into a frame sequence and saves the frames (color + depth), graph, and node rotations + translations to some directory
- [ ] make a pipeline option & mechanism to read node transformations instead of using the tracker to produce them
- [ ] run fusion with these settings on the generated cube sequence, assess the result

**Comment by Algomorph** [comment]
I don't think this is at all relevant at this point -- fairly certain everything this would be testing is working fine.
