### ISSUE TITLE
Test NeuralTracking generate / evaluate & assess output

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/NeuralTracking#9]
Needed to establish that environment setup (e.g. alternative PyTorch version) is not affecting output of the tracking itself.

**Comment by ahmed-akader** [comment]
Ran run_generate.sh and run_evaluate.sh with "val" split. Need to interpret reported errors.
 
> $ /bin/bash /home/ahmedabdelkader/workspace/NeuralTracking/run_evaluate.sh
>   0%|                                                                                                                                                                                                  | 0/668 [00:00<?, ?it/s]evaluate.py:106: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
> Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
>   scene_flow_mask = scene_flow_mask[0].astype(np.bool)
> evaluate.py:107: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
> Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
>   optical_flow_mask = optical_flow_mask[0].astype(np.bool)
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 668/668 [06:15<00:00,  1.78it/s]
> Graph Error 3D (mm): 24.24993734954321
> EPE 3D (mm):         20.54511622384046

**Comment by Algomorph** [comment]
Next subtask: figure out whether this actually corresponds to what we should be getting.
Strategies:
 - [ ] Try going back to the NNRT paper, see what kind of error metrics they use there and what errors they report, see if any of this  output info corresponds
 - [ ] Check online for what EPE might mean in this context
 - [ ] Try figuring out in the code how the error is computed, and from this try to infer whether the error reported is truly low.

**Comment by Algomorph** [comment]
What authors refer to as EPE 3D is just the scene flow error, i.e. distance between dense target (RGBD) points and the transformed dense source (RGBD) points after the GN optimization of the motion graph using predicted correspondences.

The Graph 3D error relies on ground truth of graph "deformations" (i.e. translations) from the DeepDeform dataset -- it's just an error in graph node translations.

The error from the "Model_A" included with the original NNRT code, when run on the validation data split, is actually in line with the error reported in the NNRT paper (AND also reported in the data available with the code). 

Validation split error (when we run the evaluation script):
Graph Error 3D (mm)                      24.24993436552625
EPE 3D (mm)                              20.545117541751452

Reported test split error:
Graph Error 3D (mm)                      30.89792276991369
EPE 3D (mm)                              26.004892088318034
